### PR TITLE
The changes to match FinCAD library results

### PR DESCRIPTION
**Pull request by abrashin**

### CODE REVIEW

**Comment by jodastephen** [comment]
Thanks for the proposed patch.

When submitting pull requests, it is good practice to avoid formatting changes. Right now, the PR appears to consist primarily of formatting changes, which makes it very hard to review. It would probably be best to push an additional commit (or new PR) reversing the formatting changes, so we can see the "meat" of the proposed change.

**Comment by abrashin** [comment]
I've just pushed a new commit with the right format. This commit is a "rewrite history" type of commit, are you able to see it?

**Comment by mobrahim** [comment]
Can you please provide a comprehensive description of the changes (a bit more than the PR title) + push some unit tests ?

**Comment by jonathansenior** [comment]
Closing due to inactivity.

**Pull request closed without merging**
